### ISSUE TITLE
Support for using formulas outside of /sw/tools/smithy/formulas

### ISSUE THREAD

**Issue by robertdfrench** [AnthonyDiGirolamo/smithy#4]
It would be nice to be able to install from a formula that is outside the main formula area, for the purpose of testing / developing formulas outside of the "production" area.

**Comment by AnthonyDiGirolamo** [comment]
You can do this by adding directories to the formula-directories section of the smithy config file. See http://anthonydigirolamo.github.io/smithy/smithy.1.html?4#SMITHY-CONFIG-FILE for an example.
